### ISSUE TITLE
Google search console - text too small to read, clickable elements too close together

### ISSUE THREAD

**Issue by gwaybio** [greenelab/lab-website-template#100]
FYI, I just got this email from `Google Search Console Team <sc-noreply@google.com>`

>Mobile Usability issues detected on waysciencelab.com
To the owner of waysciencelab.com:
Search Console has identified that your site is affected by 2 Mobile Usability issues:
Top Issues
The following issues were found on your site:
> - Text too small to read
> - Clickable elements too close together
> We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

**Comment by vincerubinetti** [comment]
You can safely ignore this. I'll elaborate more tomorrow but here's some related stack exchange posts about it:

https://webmasters.stackexchange.com/questions/127891/how-to-resolve-text-too-small-to-read-error-from-google-search-consoles-mobil?newreg=4d07206dbdba41e08de8aa1f0afe8a53

https://stackoverflow.com/questions/57095841/google-says-text-too-small-to-read-but-no-info-about-recommended-font-size
