### ISSUE TITLE
How are the tags of the publications generated?

### ISSUE THREAD

**Issue by renxinyang** [greenelab/lab-website-template#119]
Hi,
I want ask about how the tags of the publications are generated. After running auto-cite, I didn't get the tags in the output file citations.yaml. Are they manually added? Thank you!

**Comment by vincerubinetti** [comment]
Yes, you provide the tags manually. These are not something Manubot can (or should) generate automatically. You can choose what tags are most important to your website visitors, and categories your papers accordingly.

See this page of the docs:
https://github.com/greenelab/lab-website-template/wiki/Citations

In `sources.yaml`, just provide a `tag` field alongside the paper's `id` with a list of strings.

**Comment by renxinyang** [comment]
Thank you very much for your quick response!
