### ISSUE TITLE
Ignore manubot cite errors when source is from a metasource?

### ISSUE THREAD

**Issue by LaBiOmicS** [greenelab/lab-website-template#121]
When trying to update our articles by Auto Cite I see the error below:

Run python ./auto-cite/auto-cite.py
## WARNING
Generating csl_item for 'eid:2-s2.0-8504142836[7](https://github.com/LaBiOmicS/labiomics.github.io/runs/7062873948?check_suite_focus=true#step:5:8)' failed due to a NotImplementedError:
Manubot does not know how to generate a csl_item for 'eid:2-s2.0-[8](https://github.com/LaBiOmicS/labiomics.github.io/runs/7062873948?check_suite_focus=true#step:5:9)5041428367'
COMPILING LIST OF SOURCES TO CITE
RUNNING ORCID PLUGIN
(...)
Source 20 of 36 - eid:2-s2.0-85041428367
Using Manubot to generate new citation
Couldn't parse Manubot response
Error: Process completed with exit code 1.

I understand the error is related to Manubot not recognizing "eid" citations, however these are not from my quote list and apparently are from another user using the bot (if I understand correctly).

How can I solve this problem?

**Comment by vincerubinetti** [comment]
Okay I took a look at your failed github actions workflow run here:
https://github.com/LaBiOmicS/labiomics.github.io/runs/7062873948?check_suite_focus=true

It seems like the `eid` reference is getting generated from the ORCID plugin. Maybe this what you were referring to with "another user using the bot"?
