### ISSUE TITLE
Page not loading CSS after fork

### ISSUE THREAD

**Issue by goallabuci** [greenelab/lab-website-template#131]
I followed the steps from getting started and realize my page is only loading HTML text and broken image links.

Should I toggle anything else to load the website properly? I am using GitHub pages and renamed the repo to match the username.

**Comment by vincerubinetti** [comment]
Did you [set `baseurl` in your config file](https://github.com/greenelab/lab-website-template/wiki/Get-Started#set-up-your-url)? What you describe is what happens when you don't. That is one of the steps in "Getting Started".

**Comment by vincerubinetti** [comment]
https://github.com/goallabuci/goallabuci.github.io/commit/04c8beb572f75eb499145aed49defdb27e3e08ca
