### ISSUE TITLE
Cannot open netlify's deploy

### ISSUE THREAD

**Issue by rcarcamo-dot** [greenelab/lab-website-template#136]
Hi,

I have been trying to use from scratch the template you provided following the instructions. However, every time I deploy it, I cannot open the link generated by netlify. I have also tried to use the webs from people who have succesfully use the template, but with the same result. 

Do you know what can be the reason?

Thank you very much for your time.

**Comment by vincerubinetti** [comment]
Could you link to the repo you are referring to? Is it this one: https://github.com/rcarcamo-dot/lab-website

Are you using Netlify to do pull request previews (as written in the template docs) or are you also trying to use it for the live production version of the site? Did you add the special build command [as instructed here](https://github.com/greenelab/lab-website-template/wiki/Get-Started#set-up-previews)? 

Can you share the Netlify link that is not working? Can you share screenshots of the Netlify interface that you're seeing?

I'll need a lot more information to be able to help you.

**Comment by vincerubinetti** [comment]
Closed for inactivity. Please reply with more information and I'll reopen until the issue is resolved.
