### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by laterz-f** [greenelab/lab-website-template#144]
Hi there, 
first of all awesome template! I am having great fun using it, works like a charm.
One thing though, approximately 30 minutes ago I started being unable to make new commits.
I get this error:
 
/usr/bin/docker pull ghcr.io/actions/jekyll-build-pages:v1.0.6
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
Error: Docker pull failed with exit code 1

And the build job fails. Is it a docker server problem? Did you have this issue before and does it fix itself?
Thanks!

**Comment by vincerubinetti** [comment]
It looks like there is a GitHub outage at the moment:

https://www.githubstatus.com/

I'm going to guess that this is the issue. Im not at a computer right now but if this is still happening when I get back I'll investigate.

**Comment by laterz-f** [comment]
Yes, I think so. Just retried and worked fine 👍🏻
