### ISSUE TITLE
Truly relative URLs (relative to current file/page) not supported

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/lab-website-template#145]
Sparked by this PR, where a relative path with `..`s caused image links to break:
https://github.com/CU-DBMI/set-website/pull/8/files

The "workaround" is to just say that users must always specify urls relative to the root of their repo. This is OK, but not ideal. It lacks flexibility and will definitely catch more people off guard in the future. It should work just like paths regularly do in HTML or any other directory system.

This is because I'm using the built-in Jekyll/Liquid filter `relative_url` in all of my components. However, this filter doesn't actually resolve relative urls, it just prepends `baseurl` to them.

See this issue for a discussion:
https://github.com/jekyll/jekyll/issues/6360

We can get the directory that the component is being used from with `page.dir`. Then we can use one of the solutions listed in that issue, either the plugin one or the gist/include one.

https://github.com/benbalter/jekyll-relative-links ?

**Comment by vincerubinetti** [comment]
On further thought, I think this is something we won't implement. My reasoning:

- A URL can be specified in many places: `_data`, `.md` front matter, component parameters, in raw markdown, etc. When "relativizing" the URL, it will be relative to the place the URL is _consumed_, not the place it is _defined_. Maybe I could make the relativizing method smart enough to determine the place of definition, but it would be complicated and brittle.
- I envision this adding more confusion to users. For example, a user could see a `../image.jpg` link in a `_data` file and understandably think it refers an image one folder up (in the root), but really when that data file gets consumed/listed, it's in a sub-page like `/team/join` and so it's actually going to refer to an image in `/team`. They would have to look at a completely different part of the site/repo to see where that data is consumed. 
- Data and collections can be consumed in multiple different places. A common example of this is `citations.yaml`, where you might display only a small sub-set of noteworthy papers on your `/research` page, but display the entire list on `/cv` or a bio page. Because of this, relative links in data and collections could now refer to different files each time they are consumed. I suppose this could be considered a feature, but I think it's more likely to lead to insidious user frustration.
- Where this would be most useful is when you have a lot of nesting and sub-folders, but I don't think most people do this.

Instead I will add a clear note about this in the docs saying that all links to pages/images/etc. within the repo must be relative to the root, not relative to the current file.

But I could go either way on this, so if there are more users who want this, we could reopen this issue. So far it seems no one else has encountered or complained about not being able to do relative paths.

**Comment by d33bs** [comment]
@vincerubinetti - thank you for the thorough notes and thoughts above! I agree that a clear note within the docs seems appropriate given what you mention. Depending on documentation structure, maybe an "FAQ" or placeholder issue with a related challenges when a relative path has been used (for ex. "Why aren't my images appearing?") and the solution could be helpful (this is only a suggestion).
