### ISSUE TITLE
Pick what content of blog post gets used as excerpt

### ISSUE THREAD

**Issue by falquaddoomi** [greenelab/lab-website-template#154]
Basically, in Dave's ToTW he includes a disclaimer as quoted text at the beginning of each post. Unfortunately, this text appears as the summary for every blog post in the list of posts.

I'm not sure if this should be considered a problem with lab-website-template, as I could imagine wanting a quote to be part of the summary text in other cases...maybe we need a way to identify preamble text versus body text, or just to find another way to mark up disclaimers that should be excluded from the summary?

**Comment by vincerubinetti** [comment]
References:

https://talk.jekyllrb.com/t/blog-excerpts-can-i-exclude-stuff/2563/2
https://stackoverflow.com/questions/32444079/jekyll-post-excerpt-how-to-remove-the-first-paragraph

Off the cuff, I think the best way would be to have the user manually specify an `excerpt` in the frontmatter of the post where they want to not use the default.
