### ISSUE TITLE
Separate title from subtitle in config show-text

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/lab-website-template#160]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Version of Lab Website Template you are using

1.0.0

### Description

The Pividori lab has a logo image with their title, but not their subtitle. `_config.yaml` has a `logo-text` flag that hides both the title and subtitle next to the logo, but sometimes a user might want to hide either or.

Very easy to add. Naming the params is the hardest part. `logo-title/subtitle`? How will someone interpret that flag, "does my logo have a title/subtitle" or "should we show a title/subtitle next to the logo"? `show-title/subtitle`? Maybe. They might expect setting it to `false` to hide it everywhere -- in the tab name and meta tags, not just the header -- when it won't.

**Comment by miltondp** [comment]
Maybe an option could be `logo-has-title` (and `logo-has-subtitle`). By default they are `false`, so the title/subtitle are shown (not shown otherwise).
