### ISSUE TITLE
First time setup exits with code 127

### ISSUE THREAD

**Issue by dortheimer** [greenelab/lab-website-template#180]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/Architectural-Artificial-Intelligence/aairl-lab-website/

### Description

Error message in the "first-time-setup" action:

```bash
Rename files:
Run \ mv .github/user_pull_request_template.md .github/pull_request_template.md
/home/runner/work/_temp/a0065495-18f9-4084-b8ef-e26891e4c005.sh: line 1:  mv: command not found
Error: Process completed with exit code 127.
```

I have used the code as a template and followed the installation process according to the documentation.

**Comment by dortheimer** [comment]
This issue was caused by a different action called "on push to main" that failed.
The issue was fixed by re-running the "on push to main" action.

**Comment by vincerubinetti** [comment]
This is very strange and I'm still a little confused by it. I don't know why the `mv` command, something that is built into most operating systems, would not be found as a valid command...

It looks like both of your `first-time-setup` runs failed, but hopefully you've got things set up now how you need them.

I see that you made a commit to main _before_ you ran the first time setup. This is not the intended order of things in the instructions, but I don't know why it would've caused any issues. I'll experiment with this when I have time to determine the cause and fix.

**Comment by vincerubinetti** [comment]
Ah this is the same issue as #181. See there for more details. The error message here is misleading.
