### ISSUE TITLE
How to adjust the after-paragraph space?

### ISSUE THREAD

**Issue by sterding** [greenelab/lab-website-template#218]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Description

I am wondering if you have a way to decrease the after-paragraph space in the citation? Below are two examples, one from my site and one from the greenelab.com. It's obvious that greenelab one has smaller after-paragraph space and looks nicer! I tried to change the `  --spacing: 2;` in _styles/-theme.scss, but that's for within-paragraph line space, not for after-paragraph space. 

![image](https://github.com/greenelab/lab-website-template/assets/682270/d41e40fb-4559-430c-b96d-30349a397c40)

![image](https://github.com/greenelab/lab-website-template/assets/682270/f4aa179c-6dfa-4972-b824-61385facd661)

**Comment by vincerubinetti** [comment]
In the future, for questions like this that are not bugs, please use a [discussion](https://github.com/greenelab/lab-website-template/discussions).

To adjust this spacing, you can adjust the value of `gap: 15px;` in the `.citation-text` class in `_styles/citation.scss`.

**Comment by vincerubinetti** [comment]
It's also pretty clear that something odd is going on in your (first) screenshot. The gap should not be that wide. What browser are you using? What other CSS (.scss) modifications have you made? This is why I really need to see the repo and source code to help you. There are many parts to the template and things can affect each other.

**Comment by sterding** [comment]
Thanks for your help, Vincent. I’ll push the code to repo and share with you. Sent from my iPhoneOn Oct 27, 2023, at 12:05 PM, Vincent Rubinetti ***@***.***> wrote:﻿
It's also pretty clear that something odd is going on in your (first) screenshot. The gap should not be that wide. What browser are you using? What other CSS (.scss) modifications have you made? This is why I really need to see the repo and source code to help you. There are many parts to the template and things can affect each other.

**Comment by vincerubinetti** [comment]
This 

> It's also pretty clear that something odd is going on in your (first) screenshot. The gap should not be that wide. What browser are you using? What other CSS (.scss) modifications have you made? This is why I really need to see the repo and source code to help you. There are many parts to the template and things can affect each other.

See this comment for the cause: https://github.com/greenelab/lab-website-template/issues/217#issuecomment-1784256140

**Comment by sterding** [comment]
Thank you so much, Vincent. The space looks perfectly now!!
