### ISSUE TITLE
Bug in `object_items` plugin filter func

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/lab-website-template#232]
See https://github.com/greenelab/lab-website-template/discussions/231

In the `tags.html` component, it's possible to pass it a raw string for the `tags` param, and that results in `object_items` returning an empty list. A quick fix is to simply return `object` instead of `[]`.

A better fix might might be to pull out the `join: "," | split: ","` filters (that I'm doing in many place to normalize things to an array) into its own filter.

**Comment by bvoightlab** [comment]
Quick note that I attempted the change of `return []` to `return object` in `/_plugins/misc.rb` L17; this works initially for the first display. However, once you click one of the buttons to apply the filter (this is successfully), the tag buttons no longer display.

**Comment by vincerubinetti** [comment]
[The tags component will just link to wherever you tell it to](https://github.com/greenelab/lab-website-template/blob/main/_includes/tags.html#L21), and at the moment in your `tools.md` you're specifying `link="https://voightlab.com/tools/"`. I recommend you always do relative paths like `/tools` or `tools`. [See more here](https://greene-lab.gitbook.io/lab-website-template-docs/basics/write-basic-content#advanced).

**Comment by bvoightlab** [comment]
Yep! I just caught that and realized that was much less good. Thanks for this! -BV
