### ISSUE TITLE
Compatibility With Academic Icons.

### ISSUE THREAD

**Issue by sbbecongresso** [greenelab/lab-website-template#249]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/sbbecongresso/sbbecongresso.github.io

### Version of Lab Website Template you are using

1.2.1

### Description

Hello.

Thanks a lot for the great tool. I am a Brazilian researcher and I have been using your template to create a webpage for a congress that will happen in Brazil. It is common for Brazilian researchers to use this governmental platform (https://lattes.cnpq.br/) and it would be great if I could have its logo on our page. Unfortunately, Font Awsome does not provide it. However, Academic Icons (https://jpswalsh.github.io/academicons/) does! 

Thus, I was wondering if there was a way to use Academic Icons on this template. I would very much appreciate any recommendations you could provide.

Thanks very much in advance, George.

**Comment by vincerubinetti** [comment]
Their page here describes how you would do that:
https://jpswalsh.github.io/academicons/

You can put the `<link>` to their stylesheet in `_includes/fonts.html`, or you can download the stylesheet and just put it in `/_styles`.

Then you can use it any `.md` file like they show in their docs with `<i>`, or you can use the template's [icon component](https://greene-lab.gitbook.io/lab-website-template-docs/basics/components/icon).

**Comment by sbbecongresso** [comment]
Thanks a lot! 
I confirm this works :)
