### ISSUE TITLE
Support forks after all?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/lab-website-template#25]
Templates are good because you can get a copy of the repo without all of the commit history. If you're starting a new website for your lab, you don't care about the commit history of the template itself; you care about your own commit history.

However, if you need to pull updates from the template, it's a huge PITA because you [have to manually resolve merge conflicts](https://stackoverflow.com/a/56577320/2180570). Also, you end up getting a bunch of extra commits in the PR from the template anyway, [like this](https://github.com/greenelab/greenelab.com/pull/23).

Perhaps we could explain [here](https://github.com/greenelab/lab-website-template/wiki/Get-Started) that you can do a template or a fork, depending on what you want?

Or maybe there's some workaround where you can get easy/automatic merges, and without extra irrelevant commits...

@dhimmel (git expert) @cgreene @dongbohu do you have any thoughts about this?

**Comment by dhimmel** [comment]
You could document the following options:

1. use GitHub template features to start with a clean commit history but without the ability to automatically pull updates
2. using a clone approach [like Rootstock](https://github.com/manubot/rootstock/blob/2191d929a12a233347ee79c673b8f2971c10e6dd/SETUP.md), which allows for pulling updates, but also requires local git commands and keeps this repo's commit history

**Comment by vincerubinetti** [comment]
Thank you for the insight Daniel. I was hoping there was some obscure Git or GitHub trick that would allow us to get best of both worlds (clean commit history and easy updates). But if you don't know it, it probably doesn't exist!

I'll opt for changing the documentation to just explaining the pros/cons of each, and letting the user decide.

**Comment by vincerubinetti** [comment]
Updated this page to explain the differences:

https://github.com/greenelab/lab-website-template/wiki/Get-Started
