### ISSUE TITLE
Unable to add new tabs in the website

### ISSUE THREAD

**Issue by aditya-sarkar441** [greenelab/lab-website-template#26]
I was trying to add more tabs to the lab website. But I am not sure how to add it. I tried making a folder and then added a .md file with some contents, but on pushing it on GitHub, no new tab was created. Please help me out with this.

**Comment by vincerubinetti** [comment]
[This section](https://github.com/greenelab/lab-website-template/wiki/Basic-Editing#generic-folders) of the documentation explains how to add different pages by adding `.md` files, which you have already done, and also explains that you need to edit the [header component](https://github.com/greenelab/lab-website-template/wiki/Components#header) to add the link you want.

**Comment by aditya-sarkar441** [comment]
@vincerubinetti Thanks a lot !! It worked. You can close this issue.

**Comment by vincerubinetti** [comment]
Thank you for raising the question. In the future, when asking these questions, it would be helpful to us to know where you got stuck in the Documentation so we can improve it. At this stage in the template's development, we're very interested in suggestions for how to make the documentation easier to read and follow.

**Comment by aditya-sarkar441** [comment]
Sure. Thanks !!
