### ISSUE TITLE
On schedule update citations fails

### ISSUE THREAD

**Issue by snaqvi1990** [greenelab/lab-website-template#263]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/snaqvi1990/naqvilab/

### Version of Lab Website Template you are using

1.1.6

### Description

Hi there,

The automatic citation update was running fine for a few months, but it recently started failing for some reason. See attached error message. Any idea what's going on?

Thanks,
Sahin

![image](https://github.com/greenelab/lab-website-template/assets/7546459/3e709b99-e588-4c6a-8902-7df2ff4a8e6e)

**Comment by vincerubinetti** [comment]
Since this is certainly an upstream issue, going to close. But I'm happy to help debug if you want to keep commenting. I see you updated the action version in your workflow. I believe you should be able to manually rerun the workflow to see if it works.

**Comment by snaqvi1990** [comment]
Thanks! The workflow works now
