### ISSUE TITLE
Add text option to social link component?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/lab-website-template#28]
Per [this comment](https://github.com/greenelab/greenelab.com/pull/24#issuecomment-758078355), maybe social links on team member bio page would be easier to read/recognize if they had text in addition to the icon?

This would work with a `text` boolean option, like the [role component](https://github.com/greenelab/lab-website-template/wiki/Extra-Components#role) has, and would be set to true for `_layouts/member.html` and left false elsewhere (eg, don't want the text next to the icons in the footer).

**Comment by cgreene** [comment]
It turns out that ublock origin was blocking the social icons for some reason... no idea why.

**Comment by vincerubinetti** [comment]
That's really weird. Were other icons on the website being shown, like the icons in the footer? Maybe it was blocking the loading of the whole FontAwesome font resource...

**Comment by cgreene** [comment]
Footer is empty too!

**Comment by cgreene** [comment]
![Screen Shot 2021-01-11 at 11 06 45 AM](https://user-images.githubusercontent.com/542643/104220702-1dfec800-53fd-11eb-8163-d82ba743ff60.png)

**Comment by vincerubinetti** [comment]
Wow. And the PhD student and "Ben's papers" icons are still working just fine.

Can you open ublock and the console to get me more information? You're sure it's ublock causing this?

**Comment by cgreene** [comment]
disable ublock and reload gives this

![Uploading Screen Shot 2021-01-11 at 11.10.09 AM.png…]()

**Comment by cgreene** [comment]
when enabled, ublock says:
Blocked on this page
0 (0%)

**Comment by cgreene** [comment]
Toggling cosmetic filters is enough to make them appear/disappear

![Screen Shot 2021-01-11 at 11 13 03 AM](https://user-images.githubusercontent.com/542643/104221368-06740f00-53fe-11eb-9043-897fd57cbd5c.png)

**Comment by vincerubinetti** [comment]
That is very odd. You're on Firefox and MacOS right? I can't reproduce this in any of my browsers. I think this might be too specific and upstream for us to address? But if you want to troubleshoot it, can you take a screenshot of the console to see if there are any error messages, and can you also right click and inspect the footer and expand the elements so I can see them, like this:

![image](https://user-images.githubusercontent.com/8326331/104221804-6f17b780-540f-11eb-89fb-fc623790b84d.png)

**Comment by cgreene** [comment]
MacOS Big Sur 11.1
Chrome Version 87.0.4280.88 (Official Build) (x86_64)
uBlock Version 1.32.4

**Comment by vincerubinetti** [comment]
Deciding not to do this to keep a cleaner look. We can always reopen and add this if someone requests it.
