### ISSUE TITLE
Update ruby/setup-ruby action

### ISSUE THREAD

**Issue by dmreslab** [greenelab/lab-website-template#285]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/dmreslab/DM-res-lab

### Version of Lab Website Template you are using

1.2.2

### Description

Hi, I used your templete for my research lab homepage. But today, I edited my lab but it gives me following error. I thought I might mistake conducting something, but I did a revert three weeks ago commit. And it gives me same error. I think it is related to ruby version in the github pages and local codes. What should I do? Please solve the issue.

Thanks,
Sang Ho Park
 
Run ruby/setup-ruby@v1.172.0
Error: The current runner (ubuntu-24.04-x64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
In such a case, you should install Ruby in the $RUNNER_TOOL_CACHE yourself, for example using https://github.com/rbenv/ruby-build
You can take inspiration from this workflow for more details: https://github.com/ruby/ruby-builder/blob/master/.github/workflows/build.yml
$ ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
Once that completes successfully, mark it as complete with:
$ touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete
It is your responsibility to ensure installing Ruby like that is not done in parallel.

**Comment by dmreslab** [comment]
@vincerubinetti 
Thank you so much for your helpful answer! I followed your suggestion to update the ruby/setup-ruby action to version 1.196.0 in my .github/workflows/build-site.yaml file, and it resolved the issue. I really appreciate your quick and effective support.
I'm glad to say that I'll continue using this lab template in the future. It's been very useful for my work, and with your assistance, it's now running smoothly again. Thanks for maintaining such a helpful resource!

**Comment by vincerubinetti** [comment]
Glad the fix was simple. Going to reopen this because the change need to make it into the base template as well.

**Comment by dmreslab** [comment]
@vincerubinetti I am newbie in frontend dev, but I think in docker file should be edited also. 
[.docker](https://github.com/greenelab/lab-website-template/tree/main/.docker)
/Dockerfile
Here, how about edit ruby version from
# start with official ruby docker image as base
FROM ruby:3.1.2

to 
# start with official ruby docker image as base
FROM ruby:3.1.4
?

I think it is also edited. 

Thanks.

**Comment by vincerubinetti** [comment]
Possibly. It depends if the issue is with Ruby itself or just the `setup-ruby` action. I'm guessing it's the latter. But I'll check if there's any issue with the Ruby docker image.

Regardless though, might as well bump it up to the latest version.

**Comment by christianbrodbeck** [comment]
It looks like I'm running into this issue even after updating to the latest version of the template (https://github.com/christianbrodbeck/lab-website/actions/runs/13160861542/job/36729028105) and setting `uses: ruby/setup-ruby@v1.196.0`. (https://github.com/christianbrodbeck/lab-website/actions/runs/13156276010/job/36714122115?pr=18). Any idea where to look next?

**Comment by vincerubinetti** [comment]
@christianbrodbeck You're not running `setup-ruby@v1.196.0`, you're still on the old version.


<img width="200" alt="Image" src="https://github.com/user-attachments/assets/a1a53fe0-4567-4090-b80e-3a2fd290766f" />

I'm guessing this is because that's a pull request workflow run. When opening a PR, GitHub will run any PR workflows _as they currently are on `main`_, not as they are in the PR (even if they were changed in the PR). This is something like a security measure on GitHub's part.

**Comment by jharenza** [comment]
thank you, this also helped me!
