### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by miltondp** [greenelab/lab-website-template#4]
I think it would be nice to have an RSS feed for the site. It could cover the blog, research and resources.

**Comment by vincerubinetti** [comment]
We already enable this by default with this plugin:
https://github.com/jekyll/jekyll-feed

`feed.xml` exists in the root of the built site, for example: 
https://www.greenelab.com/feed.xml

I don't know how RSS or Atom work. I suppose we should put a link to this somewhere? How does one make an RSS link that is useful for users.

**Comment by miltondp** [comment]
Oh cool! I didn't know that. I used a plugin I have in chrome to search for feed links and it didn't find any. Now it worked by providing the feed.xml file. What about a link to that file along with the Twitter, Instagram, etc links?

**Comment by vincerubinetti** [comment]
Oh okay so a link to the feed xml file is all RSS apps/clients/extensions usually need to subscribe? If so that's an easy fix, yes I'll add an RSS social icon at the bottom of the site.

**Comment by vincerubinetti** [comment]
Okay see if your extension picks up the RSS feed on this site:
https://greenelab.github.io/lab-website-template/

I've put an invisible rss tag on the site. I've also put in an actual visible link to the feed in the footer, but commented it out so users can have it there if they want.

**Comment by miltondp** [comment]
Yes, my extension picks up the RSS feed! Awesome!
