### ISSUE TITLE
Creating clickable tags

### ISSUE THREAD

**Issue by eastonwhite** [greenelab/lab-website-template#41]
New to this template, but it looks great. Are there any plans to make the tags clickable in order to filter the Research or Blog pages? It would then also be helpful to have list of all tags used on either page that could be clickable on the right or bottom of a page.

**Comment by vincerubinetti** [comment]
I had thought about this. Was waiting to see if anyone was interested. FWIW right now you can search for tags and they'll come up:

![image](https://user-images.githubusercontent.com/8326331/112765878-4a2dec00-8fdd-11eb-89a4-f57dc7cc68bf.png)

Though it also brings up matches just in the plain text of the citation.

To do a real solution (only papers and blog posts with a certain tag) would take a bit more work but definitely doable. Just need to think of the cleanest way to do it. This will probably be the next significant feature I add.

**Comment by eastonwhite** [comment]
It is nice that the tags still come up with the search. Glad you are interested in adding this feature.
