### ISSUE TITLE
template button not generating

### ISSUE THREAD

**Issue by graim** [greenelab/lab-website-template#6]
No option to create a new repository from template, just to clone the repository

**Comment by vincerubinetti** [comment]
Can you describe what you're doing? I have this button checked:

![image](https://user-images.githubusercontent.com/8326331/96803361-1a4d3d80-13da-11eb-9516-2ba224395037.png)

And I seem to be able to create a new repo:

![image](https://user-images.githubusercontent.com/8326331/96803386-30f39480-13da-11eb-9ed0-b3d635e7cfa5.png)

**Comment by graim** [comment]
Not sure what changed, but the template option is showing up for me now. Thanks!

**Comment by vincerubinetti** [comment]
Might be a GitHub bug. Templates are still relatively new.
