### ISSUE TITLE
Netlify Publish Directory

### ISSUE THREAD

**Issue by benjamindkilleen** [greenelab/lab-website-template#65]
In the Netlify instructions, the "Publish directory" needs to be set to `_site`, otherwise there's a 404 error. This should be noted in the "Getting Started" wiki page.

**Comment by vincerubinetti** [comment]
In my experience Netlify has always set this field automatically, presumably detecting that the repo is a Jekyll site automatically. Did it not do that for you?

**Comment by benjamindkilleen** [comment]
For some reason it didn't, although I configured the build command correctly. It's now working after changing the directory, so maybe just making a note?

This is a great template by the way! Thanks so much for all the hard work!
