### ISSUE TITLE
Tooltips do not always align with text

### ISSUE THREAD

**Issue by cgreene** [greenelab/lab-website-template#69]
![Screen Shot 2021-04-28 at 1 34 56 PM](https://user-images.githubusercontent.com/542643/116462338-92cc0580-a826-11eb-92b7-d8ecd79dc88c.png)

On both greenelab.com and tislab-new on safari Version 14.0.3 (16610.4.3.1.7) I see this

**Comment by vincerubinetti** [comment]
Most likely due to this line:
https://github.com/greenelab/lab-website-template/blob/main/css/tooltip.scss#L16

Even though [Safari supposedly supports it](https://developer.mozilla.org/en-US/docs/Web/CSS/max-content).
