### ISSUE TITLE
Move to multiple-output files setup for auto-cite?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/lab-website-template#76]
Perhaps also consider going to a separate citation output file system, to simplify [this diagram](https://user-images.githubusercontent.com/8326331/119867215-a765f100-beeb-11eb-8698-2ad4fa337f91.png) into a single layer... Then maybe the `{% include list.html data="citations" component="citation" filter="page: tim-member" %}` solution wouldn't be necessary, and you could just do `{% include list.html data="tim-member-citations" component="citation" %}`. 

Might also make the auto-cite pipeline more clear to the user at first glance. One input file -> one output file. Like `sources-2020.yaml` -> `sources-2020_citations.yaml`

**Comment by vincerubinetti** [comment]
A downside of this would be that if you want to display everything in one spot, it'd a bit more verbose:

```
{% include list.html data="sarah-citations" ...
{% include list.html data="tim-citations" ...
{% include list.html data="alex-citations" ...
{% include list.html data="2020-citations" ...
{% include list.html data="2021-citations" ...
```

But... there would be no reason to get rid of the metadata pass-through and `filter="page: tim-member"` method even if we switched to this. So user's could use whatever method was more convenient.

Needs more thought. And input from any users is welcome.

**Comment by vincerubinetti** [comment]
@dongbohu @cgreene @dhimmel I know you're not directly related to this project or the target users, but I would love your thoughts on this if you have time, as I've been stuck in my own head with this template for a long time.

**Comment by cgreene** [comment]
I wonder if it makes sense to think about citations from a tagging point of view where tags could be applied at the item, source, or plugin level, but multiple tags could be applied. In our case, I think we'd apply the `greenelab` tag to everything from my ORCID source as well as anything from the sources plugin. Lab member pages could, by default, display anything with a tag that matches the user id. Then their ORCID source could be configured to assign that tag.
