### ISSUE TITLE
how to change icon in browser tab?

### ISSUE THREAD

**Issue by jxchen01** [greenelab/lab-website-template#81]
![image](https://user-images.githubusercontent.com/7811075/123376299-1f512680-d53f-11eb-8c2a-9adc62eebcef.png)

Is it possible to change the icon/picture in this tab?

**Comment by cgreene** [comment]
These are favicons. You could change the location in which they are stored:
https://github.com/greenelab/lab-website-template/blob/8916d477c25f1d40594a9e2744a27957b40a5fd0/_includes/favicons.html
Alternatively, the easiest path is probably to change the icons here in your fork:
https://github.com/greenelab/lab-website-template/tree/main/favicons

**Comment by vincerubinetti** [comment]
https://github.com/greenelab/lab-website-template/wiki/Basic-Editing#favicons
