### ISSUE TITLE
Getting started wiki step 6 baseurl

### ISSUE THREAD

**Issue by gwaygenomics** [greenelab/lab-website-template#92]
Hi @vincerubinetti - first, thanks for putting this resource together! I can tell that it will be quite useful to me.

I am setting up https://github.com/WayScience/waysciencelab.com and I noticed one quick thing that could have saved me ~20 min of troubleshooting:

The current text reads: "In the config file, set baseurl whatever you named your site repo, e.g. /your-lab-website, and publish the changes."

I think all you need to do is add a new sentence, something like: "If you're using a custom url and CNAME, set `baseurl: ""`

**Comment by vincerubinetti** [comment]
Hello Dr. Way, good to have you with us again!

This information was in a "hook up a custom domain" section on that same docs page further down. However, I've re-written the whole page to hopefully be a little clearer:

https://github.com/greenelab/lab-website-template/wiki/Get-Started

**Comment by gwaygenomics** [comment]
Thanks @vincerubinetti - looks clearer!
